configuracion/urls.py
from django.contrib import admin
from django.conf import settings   
from django.conf.urls.static import static 
from django.urls import path, include
from django.conf.urls import handler404
from core.inicio.views import page_not_found404
# handler404 = page_not_found404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.inicio.urls')),
    path('login/', include('core.login.urls')),
    path('erp/', include('core.erp.urls')),
    path('user/', include('core.user.urls')),
    path('solicitudes/', include('core.solicitudes.urls')),
    path('security/', include('core.security.urls')),
    path('group/', include('core.group.urls')),
    path('chat/', include('core.chat.urls')),
    path('notificacion/', include('core.notificaciones.urls')),
    path('reportes/', include('core.reportes.urls')),
    path('aprobaciones/', include('core.aprobaciones.urls')),
    path('customize/', include('core.ui_customizer.urls'))
]
#agregaros al  urlpatterns la url de las imagenes
#if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/user/urls.py
from django.urls import path
from core.user.views.user.views import *


app_name = 'user'

urlpatterns = [
    # user
    path('list/', UserListView.as_view(), name='user_list'),
    path('add/', UserCreateView.as_view(), name='user_create'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    # path('change/group/<int:pk>/', UserChangeGroup.as_view(), name='user_change_group'),    
    path('profile/', UserProfileView.as_view(), name='user_profile'),
    path('change/password/', UserChangePasswordView.as_view(), name='user_change_password'),
]

core/erp/models.py
from datetime import date, datetime
# Django
from django.db import models
from django.utils.text import capfirst
from django.contrib.auth.models import User
from django.contrib.admin.models import LogEntry
from configuracion.settings import MEDIA_URL, STATIC_URL, AUTH_USER_MODEL
from core.erp.choices import *
from core.audit_log.mixins import AuditMixin
from django.forms import model_to_dict

#INVENTARIO
class Categoria(AuditMixin, models.Model):
    nombre = models.CharField(max_length=250, unique=True, verbose_name="Nombre de la categoria")    
 
    def __str__(self):
        return self.nombre
    
    def toJSON(self):
        item = model_to_dict(self)
        return item

    class Meta:
        ordering=['-id']
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"

class Marca(AuditMixin, models.Model):
    marca=models.CharField(max_length=100, unique=True, verbose_name='Marca')
    created=models.DateTimeField(auto_now_add=True, verbose_name='Creación')
    updated=models.DateTimeField(auto_now_add=True, verbose_name='Ultima modificación')
   
    def __str__(self):
        return f'{self.id} - {self.marca}'
    
    def toJSON(self):
        item = model_to_dict(self)
        return item

    class Meta:
        ordering=['marca']
        verbose_name='Marca'
        verbose_name_plural='Marcas'

class Modelo(AuditMixin, models.Model):
    marcas=models.ForeignKey(Marca, on_delete=models.CASCADE, null=True, blank=True, related_name='marca_model_set', verbose_name='Marca')
    modelo=models.CharField(max_length=100, unique=True, verbose_name='Modelo')
    created=models.DateTimeField(auto_now_add=True, verbose_name='Creación')
    updated=models.DateTimeField(auto_now_add=True, verbose_name='Ultima Modificación')    

    def toJSON(self):
        item = model_to_dict(self)
        item['marcas'] = self.marcas.toJSON()
        return item

    class Meta:
        ordering=['modelo']
        verbose_name='Modelo'
        verbose_name_plural='Modelos' 

    def __str__(self):
        return self.modelo
      
class Unidad(AuditMixin, models.Model):
    nombre=models.CharField(max_length=150, unique=True, verbose_name='Nombre Unidad')
    direccion=models.CharField(max_length=200, null=True, blank=True, verbose_name='Dirección')
    rif=models.CharField(max_length=12, unique=True, null=True, blank=True, verbose_name='Rif')
    ced_resp=models.CharField(max_length=10, unique=True, null=True, blank=True, verbose_name='Cedula')
    nombrejefe=models.CharField(max_length=150, null=True, blank=True, verbose_name='Nombre Responsable')
    email=models.EmailField(max_length=50, null=True, blank=True, verbose_name='Email')
    tlf=models.CharField(max_length=26, null=True, blank=True, verbose_name='Telefonos')
    tipo_unidad= models.CharField(max_length=25, choices=tipounidad_choices, null=True, blank=True, verbose_name='Tipo de Unidad')
    solic_almacen=models.BooleanField(default=True, max_length=4, null=True, blank=True)

    def __str__(self):
        return self.get_full_name()

    def get_full_name(self):
        return '{} / {}'.format(self.nombre, self.rif)

    def toJSON(self):
        item = model_to_dict(self)
        item['tipo_unidad'] = {'id': self.tipo_unidad, 'name': self.get_tipo_unidad_display()}
        item['full_name'] = self.get_full_name()
        return item

    class Meta:
        verbose_name = 'Unidad'
        verbose_name_plural = 'Unidades'
        ordering = ['id']

class Almacen(AuditMixin, models.Model):
    codigo=models.CharField(max_length=12, unique=True, null=True, blank=True, verbose_name='Código Almacen')
    nombre=models.CharField(max_length=150, unique=True, verbose_name='Nombre Almacen')
    unidad=models.ForeignKey(Unidad, on_delete=models.CASCADE, related_name='prod_almacen_set', null=True, blank=True, verbose_name='Pertenece a:')
    cedula=models.CharField(max_length=10, null=True, blank=True, verbose_name='Cedula')
    responsable=models.CharField(max_length=150, null=True, blank=True,  verbose_name='Responsable Almacen')

    def __str__(self):
         return self.get_full_name()


    def get_full_name(self):
        return '{} - {}'.format(self.codigo, self.nombre)
    
    def toJSON(self):
        item = model_to_dict(self)
        item['unidad'] = self.unidad.toJSON()
        item['full_name'] = self.get_full_name()
        return item


    def toJSON(self):
        item = model_to_dict(self)
        return item

    class Meta:
        ordering=['nombre']
        verbose_name='Almacen'
        verbose_name_plural='Almacenes'

class GrupoCtaBienes(AuditMixin, models.Model):
    cod_grupo=  models.CharField(max_length=3, blank=True, null=True, verbose_name='Grupo')
    nombre= models.CharField(max_length=50, blank=True, null=True, verbose_name='Nombre Grupo')

    def __str__(self):
       return self.get_full_name()

    def get_full_name(self):
        return '{}-{}'.format(self.cod_grupo, self.nombre)

    def toJSON(self):
        item = model_to_dict(self)
        return item

    class Meta:
        verbose_name = 'Concepto de Grupo'
        verbose_name_plural = 'Concepto de Grupos'
        ordering = ['id']

class SubGrupoCtaBienes(AuditMixin, models.Model):
    grupo= models.ForeignKey(GrupoCtaBienes, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Grupo cuenta')
    subgrupo= models.CharField(max_length=3, blank=True, null=True, verbose_name='Subgrupo cuenta')
    seccion= models.CharField(max_length=3, blank=True, null=True, verbose_name='Sección cuenta')
    cod_grusubgrusec= models.CharField(max_length=11, blank=True, null=True, verbose_name='Auto Código ')
    denominacion= models.CharField(max_length=120, blank=True, null=True, verbose_name='Denominación')

    def __str__(self):
       return self.get_full_name()

    def get_full_name(self):
        return '{}-{}'.format(self.cod_grusubgrusec, self.denominacion)

    def toJSON(self):
        item = model_to_dict(self)
        item['grupo'] = self.grupo.toJSON()
        return item

    class Meta:
        verbose_name = 'Concepto de SubGrupo'
        verbose_name_plural = 'Concepto de SubGrupos'
        ordering = ['grupo']

class Moneda(AuditMixin, models.Model):
    codigo = models.CharField(max_length=4, unique=True, verbose_name="Código Moneda")
    pais = models.CharField(max_length=120, verbose_name="Pais de la Moneda")
    moneda = models.CharField(max_length=100, verbose_name="Nombre Moneda")
    simbolo = models.CharField(max_length=3, verbose_name='Símbolo')
    tasa_cambio = models.DecimalField(default=0.00, max_digits=14, decimal_places=2, verbose_name='Tasa de Cambio')
    status=models.BooleanField(default=True, max_length=4, null=True, blank=True, verbose_name='Activo')

    def __str__(self):
        return self.get_full_name()

    def get_full_name(self):
       return '{} - {} - {}'.format(self.codigo, self.moneda, self.pais)
    def toJSON(self):
        item = model_to_dict(self)
        item['full_name'] = self.get_full_name()
        return item

    class Meta:
        ordering=['moneda']
        verbose_name = "Moneda"
        verbose_name_plural = "Monedas"
        
class Producto(models.Model):
    codigo=models.CharField(max_length=10, null=True, blank=True, verbose_name='Código')
    nombre=models.CharField(max_length=100, verbose_name='Nombre Producto')
    descripcion=models.CharField(max_length=250, null=True, blank=True, verbose_name='Descripción')
    componentes=models.CharField(max_length=250, null=True, blank=True, verbose_name='Componentes')
    unida_medida=models.CharField(max_length=14, choices=unidamedida_choice, default='unidad', null=True, blank=True, verbose_name='Unidad Medida')  
    activo=models.BooleanField(default=1, null=True, blank=True, verbose_name='Activo')
    grupobien=models.ForeignKey(GrupoCtaBienes, on_delete=models.CASCADE, verbose_name='Grupo Bienes')
    subgrupobien=models.ForeignKey(SubGrupoCtaBienes, on_delete=models.CASCADE, verbose_name='Cuenta Bienes')
    imagen=models.ImageField(upload_to='producto/%Y/%m/%d', default='producto/sin_imagen_2.png', null=True, blank=True, verbose_name='Insertar Imagen')    
    categorias=models.ForeignKey(Categoria, on_delete=models.CASCADE, related_name='prod_categ_set', verbose_name='Categoria')
    pagaimpuesto=models.BooleanField(default=True, max_length=4, null=True, blank=True, verbose_name='Paga Impuesto')
    inventariable=models.BooleanField(null=True, blank=True, verbose_name='Inventariable')
    lote=models.BooleanField(null=True, blank=True, verbose_name='Usa Lote')
    serie=models.BooleanField(null=True, blank=True, verbose_name='Solicita Nro de Serie')
    marca=models.ForeignKey(Marca, on_delete=models.CASCADE, related_name='prod_marca_set', verbose_name='Marca')
    modelo=models.ForeignKey(Modelo, on_delete=models.CASCADE, related_name='prod_modelo_set', verbose_name='Modelo')
    moneda=models.ForeignKey(Moneda, on_delete=models.CASCADE, null=True, blank=True, related_name='prod_moneda_set', verbose_name='Moneda')
    usuario=models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='prod_user_set', verbose_name='Usuario')
  
    def __str__(self):
         return self.get_full_name()

    def get_full_name(self):
        return '{} - {}'.format(self.codigo, self.nombre)
    
    def get_imagen(self):
        if self.imagen:
            return '{}{}'.format(MEDIA_URL, self.imagen)
        return '{}{}'.format(STATIC_URL, 'producto/sin_imagen_2.png')

    def toJSON(self):
        item = model_to_dict(self)
        item['full_name'] = '{} / {}'.format(self.nombre, self.categorias.nombre)
        item['unida_medida'] = {'id': self.unida_medida, 'name': self.get_unida_medida_display()}        
        item['imagen'] = self.get_imagen()
        item['categorias'] = self.categorias.toJSON()
        item['marca'] = self.marca.toJSON()
        item['modelo'] = self.modelo.toJSON()

core/user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.forms import model_to_dict
#from core.audit_log.mixins import AuditMixin

from crum import get_current_request

from configuracion.settings import MEDIA_URL, STATIC_URL

SEXO_CHOICES = [
        ("M", 'Masculino'),
        ("F", 'Femenino'),
        ("O", 'Otros'),
    ]

class User(AbstractUser):
    dni = models.IntegerField(verbose_name="Documento de Identidad", null=True, blank=True, unique=True)
    sexo = models.CharField(max_length=1, choices=SEXO_CHOICES, blank=True, verbose_name='Sexo')
    image = models.ImageField(upload_to='users/%Y/%m/%d', null=True, blank=True, verbose_name='Imagen')
    token = models.UUIDField(primary_key=False, editable=False, null=True, blank=True)
    online = models.BooleanField(default=False)

    def get_image(self):
        if self.image:
            return f'{MEDIA_URL}{self.image}'
        return f'{MEDIA_URL}users/img/default.png'
    
    def esta_logueado(self):
        return self.is_authenticated

    def toJSON(self):
        item = model_to_dict(self, exclude=['last_login'])
        if self.last_login:
            item['last_login'] = self.last_login.strftime('%Y-%m-%d')
        item['date_joined'] = self.date_joined.strftime('%Y-%m-%d')
        item['image'] = self.get_image()
        item['full_name'] = self.get_full_name()
        item['groups'] = [{'id': g.id, 'name': g.name} for g in self.groups.all()]
        item['user_permissions'] = [{'id': p.id, 'name': p.name} for p in self.user_permissions.all()]
        return item

core/user/templates/user/access_users.html
{% load static %}
<div class="modal fade" id="access_users" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-lg cascading-modal mt-5" role="document">
		<div class="modal-content">
			<div class="modal-c-header">      
                <ul class="md-h md-header tabs-2 light-blue darken-3 d-flex align-items-center justify-content-center">
                    <h6 class="modal-title md-h title-custom text-white" id="access_user">
                        <b><i class="fas fa-info-circle"></i> <span>  Accesos de Usuario                   </span></b>
                    </h6>
                </ul> 
            </div>
			<div class="modal-body">
                <div class="container">
                    <div class="row mt-4">
                        <div class="col-12">
                            <div class="scroll-h">                                
                                <table class="table max-cont table-hover table-sm" id="tblAccessUsers" >
                                    <thead>
                                    <tr style="line-height: 12px;">
                                        <th scope="col">FECHA</th>
                                        <th scope="col">HORA</th>
                                        <th scope="col">IP</th>
                                        <th scope="col">NAVEGADOR</th>
                                        <th scope="col">DISPOSITIVO</th>
                                        <th scope="col">TIPO DE ACCESO</th>
                                    </tr>
                                    </thead>
                                    <tbody style="font-size: 13px;">
                                    </tbody>
                                </table>                                                                    
                            </div>                                               
                        </div>
                    </div>
                </div>                                                   
            </div>
            <div class="modal-footer mb-2 py-0 border-0 d-flex align-items-center justify-content-center">
                <button type="button" data-dismiss="modal" class="btn btn-out"><i class="fas fa-sign-out-alt"></i> Salir</button>      
            </div>														
		</div>                      
	</div>
</div>

core/user/templates/user/change_password.html
{% extends 'componentes/form.html' %}
{% load static %}
{% load widget_tweaks %}
{% block head %}
    {% block head_form %}

    {% endblock %}
{% endblock %}

{% block title %}
<div class="col-lg-6">

</div>

{% endblock %}

{% block content %}
    <form method="post" action="." id="formpass" name="formpass" enctype="multipart/form-data">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">                    
                    <i class="fas fa-edit"></i>                    
                    <b>{{ title }}</b>
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="action" value="edit">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label for="email">{{ field.label }}:</label>
                        {{ field|add_class:'form-control'|attr:'autocomplete:off' }}
                    </div>
                {% endfor %}
            </div>
            <div class="card-footer">                
                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-save"></i> Guardar registro
                </button>
                <a href="{{ list_url }}" class="btn btn-danger">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>
    <script>
        {% if form.errors %}
            var errors = '';
            {% for field in form %}
                {% for error in field.errors %}
                    errors += '{{ error }}\n';
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                errors += '{{ error }}\n';
            {% endfor %}
            Swal.fire({
                title: 'Error!',
                text: errors,
                icon: 'error'
            });
        {% endif %}             
    </script>
{% endblock %}
{% block javascript_form %}
<script src="{% static 'user/js/reset_password.js' %}"></script>
{% endblock %}

core/user/templates/user/create_user.html
{% extends 'componentes/form.html' %}
{% load static %}
{% load widget_tweaks %}

{% block head_form %}	
	<link rel="stylesheet" href="{% static 'lib/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
	<link rel="stylesheet" href="{% static 'user/css/form.css' %}">
	<link rel="stylesheet" href="{% static 'css/modal_style.css' %}">
	<link rel="stylesheet" href="{% static 'css/checkbox.css' %}">
{% endblock head_form %}


{% block content %}
<!-- Basic Layout -->
<form method="post" action="." enctype="multipart/form-data" id="formuser" name="formuser">  
    <div class="row">
		<div class="col-md-12">
			<div class="card main_border_top">				
				<div class="card-body">
					{% csrf_token %}
					<input type="hidden" name="action" value="{{ action }}">
					<input type="hidden" name="id" value="{{ id }}">
					<div class="container-fluid">
						<div class="row">
							<div class="col-md-9">							
								<div class="row">
									<div class="col-md-6">										
										<div class="mb-3 form-password-toggle">
											<label class="form-label custom_label" for="nombres">Nombres:</label>
											<div class="input-group">
												{{ form.first_name|attr:'autocomplete:off'|attr:'onkeypress:return Solo_Texto(event);' }}
											</div>
										</div>
									</div>
									<div class="col-md-6">
										<div class="mb-3 form-password-toggle">
											<label class="form-label custom_label" for="apellidos">Apellidos:</label>
											<div class="input-group input-group-merge">
												{{ form.last_name|attr:'autocomplete:off'|attr:'onkeypress:return Solo_Texto(event);' }}
											</div>
										</div>
									</div>
								</div>
								<div class="row g-2">
									<div class="col-md-6">
										<div class="mb-3 form-password-toggle">
											<label class="form-label custom_label" for="cedula">Cedúla</label>
											<div class="input-group input-group-merge">
												{{ form.dni|attr:'required'|attr:'autocomplete:off'|attr:'onkeypress:return Solo_Numero_ci(event);'|attr:'maxlength:8'|attr:'minlength:8' }}
											</div>
										</div>
									</div>
									<div class="col-md-6">
										<div class="mb-3 form-password-toggle">
											<label class="form-label custom_label" for="email">Email</label>
											<div class="input-group input-group-merge">
												{{ form.email|attr:'required' }}
											</div>
										</div>
									</div>
								</div>
								<div class="row g-2">
									<div class="col-md-6">
										<div class="mb-3 form-password-toggle">
											<label class="form-label custom_label" for="nombre de usuario">Nombre de Usuario</label>
											<div class="input-group input-group-merge">
												{{ form.username }}
											</div>
										</div>
									</div>
									<div class="col-md-6">
										<div class="mb-3 form-password-toggle">
											<label class="form-label custom_label" for="contraseña">Contraseña</label>
											<div class="input-group input-group-merge">
												{{ form.password|attr:'autocomplete:off' }}
											</div>
										</div>
									</div>
								</div>                                              
								<div class="row">
									<div class="col select2-gray">
										<label class="form-label custom_label" for="id_groups">Rol del Usuario</label>
										{{ form.groups|attr:'multiple:multiple'}}
									</div>
								</div>																		
								<div class="row g-2 mt-3">
									<div class="col">
										<label class="form-label custom_label" for="id_groups">Permisos Individuales</label>
										<button type="button" class="btn text-center form-control input-style btnPerms bord text-secondary">
											<span id="lenghtPerm"></span>	
										</button>									
									</div>												
								</div>																	
								<br>
								<div class="row g-2" style="margin-top: -10px;">
									<div class="col">
										<div class="custom-control custom-checkbox">
											{{ form.is_active }}
											<label for="idactive" class="custom-control-label custom_label" for="id_activo">Activo</label>
										</div>									
									</div>	
								</div>																					
							</div>
							<div class="col-md-3">
								<div class="container-fluid">									
									<div class="container-fluid">										
										{% if object.image %}
											<div style="font-size: 12px;" class="mt-1 text-center">
												<img src="{{object.image.url}}" class="img-fluid img-thumbnail shadow-sm rounded" alt="Imagen" name="imagenPrevisualizacion" id="imagenPrevisualizacion" style="margin-top: 0px; margin-bottom: 2px;" height="200px" width="200px">
											</div>
										{% else %}
											<div style="font-size: 12px;" class="mt-1 text-center">
												<img src="/media/users/img/sin_imagen_2.png" class="img-fluid shadow-sm rounded" alt="Imagen" name="imagenPrevisualizacion" id="imagenPrevisualizacion" style="margin-top: 0px; margin-bottom: 2px;" height="200px" width="200px">
											</div>
										{% endif %}																				
									</div>								
								</div>
								<div class="row mt-3">
									<div class="col-md-12">
										{{form.image|add_class:'form-control'|attr:'type:file'|attr:'id:seleccionArchivos'|attr:'style: font-size:12px'}}
									</div>
								</div>
							</div>
						</div>	
					</div>
					
				</div>
				<div class="card-footer" style="border-top: 1px solid #dee2e6;">
					<div>
						<button type="submit" class="btn btn-primary btn-bord">
							<i class="fas fa-save"></i> Guardar Registro
						</button>
						<a href="{{ list_url }}" class="btn btn-out">
							<i class="fas fa-times"></i> Cancelar
						</a>
					</div>					
				</div>
			</div>
		</div>
		
	</div>
</form>

{% include './perms.html' %}

{% endblock %}
{% block javascript_form %}
<script src="{% static 'lib/datatables/jquery.dataTables.min.js' %}" type="text/javascript"></script>
<script src="{% static 'lib/datatables-bs4/js/dataTables.bootstrap4.min.js' %}" type="text/javascript"></script>
<script src="{% static 'user/js/form.js' %}"></script>
<script type="application/javascript">    
	user.data.user_permissions = {{ perms|safe }}
</script>
<script type="application/javascript">
	const $seleccionArchivos = document.querySelector("#seleccionArchivos"),
    $imagenPrevisualizacion = document.querySelector("#imagenPrevisualizacion");
    // Escuchar cuando cambie
    $seleccionArchivos.addEventListener("change", () => {
    // Los archivos seleccionados, pueden ser muchos o uno
    const archivos = $seleccionArchivos.files;
    // Si no hay archivos salimos de la función y quitamos la imagen
    if (!archivos || !archivos.length) {
        $imagenPrevisualizacion.src = "";
        return;
    }
    // Ahora tomamos el primer archivo, el cual vamos a previsualizar
    const primerArchivo = archivos[0];
    // Lo convertimos a un objeto de tipo objectURL
    const objectURL = URL.createObjectURL(primerArchivo);
    // Y a la fuente de la imagen le ponemos el objectURL
    $imagenPrevisualizacion.src = objectURL;
    });
</script>

{% endblock %}

core/user/templates/user/list.html
{% extends 'list.html' %}
{% load static %}
{% block head_list %}
<link rel="stylesheet" href="{% static 'css/checkbox.css' %}">
<link rel="stylesheet" href="{% static 'css/modal_style.css' %}">
<link rel="stylesheet" href="{% static 'css/custom_tabs.css' %}">
{% endblock %}
{% block columns %}
    <tr style="font-size: 12px;"> 
        <th scope="col" style="width: 3%;"><label class="checkbox-container"><input type="checkbox" id="checkAll" name="checkAll"><span class="checkmark"></span></label></th>       
        <th scope="col" style="width: 8%;">IMAGEN</th>
        <th scope="col" style="width: 20%;">NOMBRE & APELLIDO</th>
        <th scope="col" style="width: 15%;">NOMBRE DE USUARIO</th>
        <th scope="col" style="width: 8%;">ESTADO</th>
        <th scope="col" style="width: 15%;">FECHA DE REGISTRO</th>
        <th scope="col" style="width: 15%;">ROLES</th>
        <th scope="col" style="width: 15%;">OPCIONES</th>
    </tr>
{% endblock %}

{% block rows %}

{% endblock %}

{% block add_modales %}
{% include 'user/modal_detail.html' %}
{% include 'user/access_users.html' %}
{% endblock %}

{% block javascript_list %}
<script src="{% static 'user/js/list.js' %}"></script>
<script src="{% static 'js/checkbox.js' %}" type="text/javascript"></script>
{% endblock %}

{% block content_list_before %}
<div class="row">
    <div class="col-lg-4">
        <div class="form-group text-secondary">           
            <div class="custom-dropdown" id="dropdown-content">
                <button class="dropdown-btn-2" id="dropdown-button"  type="button">
                    <i class="fas fa-bolt dropdown__icon"></i>
                    Acciones Rapidas 
                    <div class="dropdown__icons">
                        <i class="fas fa-chevron-down dropdown__arrow"></i>
                        <i class="fas fa-times dropdown__close"></i>
                     </div>
                </button>
                <ul class="dropdown__menu dropdown__center">
                    <li class="dropdown__item disabled">                       
                       <a class="dropdown__name">  <i class="fas fa-unlink dropdown__icon"></i> Inactivar</a>
                    </li>
                    <li class="dropdown__item is_active">
                       <a class="dropdown__name"><i class="fas fa-check-circle dropdown__icon"></i> Activar</a>
                    </li>
                    <li class="dropdown__item delete">
                        <a class="dropdown__name"><i class="fas fa-trash dropdown__icon"></i> Eliminar</a>
                     </li>
                 </ul> 
            </div>   
        </div>
    </div>
</div>
<br>
{% endblock %}

core/user/templates/user/perms.html
<div class="modal fade" id="permissionsModal" tabindex="-1" role="dialog" aria-labelledby="permissionsModalTitle"
   aria-hidden="true">
   <div class="modal-dialog modal-lg cascading-modal mt-5" role="document">
      <div class="modal-content">
         <div class="modal-c-header">      
            <ul class="md-h md-header tabs-2 light-blue darken-3 d-flex align-items-center justify-content-center">
                <h6 class="modal-title md-h title-custom text-white" id="permissionsModalTitle">
                    <b><i class="fas fa-search"></i> <span>  Búsqueda de Permiso</span></b>
                </h6>
            </ul> 
        </div>
         <div class="modal-body">
            <div class="scroll-v">
               <table id="permsTable" class="table table-hover max-cont border-top">
                  <thead>
                     <tr>
                        <th scope="col" style="width: 10%;"><label class="checkbox-container"><input type="checkbox"
                                 id="checkAll" name="checkAll"><span class="checkmark"></th>
                        <th scope="col" style="width: 90%;">PERMISOS <span class="badge badge-primary badge-pill f-11 ml-1" id="numPerms"></span></th>
                     </tr>
                  </thead>
                  <tbody>
                     <!--PERMISOS-->
                  </tbody>
               </table>
            </div>
         </div>
         <div class="modal-footer mb-2 py-0 border-0 d-flex align-items-center justify-content-center">
            <button type="button" class="btn btn-primary btn-bord btn-sm" id="assignPerms"><i class="fas fa-save"></i> Asignar
               permisos</button>
            <button type="button" class="btn btn-out btn-sm btnClose" data-dismiss="modal"><i
                  class="fas fa-sign-out-alt"></i> Cerrar</button>            
        </div>
      </div>
   </div>
</div>